# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@bemybaby'
      - run: npm install
      - run: npm run build
      - run: ls -1 packages | xargs -I% sh -c 'cd packages/%; npm set registry https://npm.pkg.github.com/@bemybaby; npm version $(npm version patch)-dev-'"$(date -u +%Y%m%d%H%M%S%6N); $(env | grep '^NODE_AUTH_TOKEN=')"' npm publish --tag=next'
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
